### ISSUE TITLE
about  cuda  support，have  cuda error

### ISSUE THREAD

**Issue by zhanghongyong123456** [absadiki/pywhispercpp#107]
I have  install succese，  when  run  example  ，have  cuda  error 
set  GGML_CUDA=1
git clone    and   pip install .

Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
True
>>> from pywhispercpp.model import Model
>>> model = Model('large-v3', print_realtime=False, print_progress=False)
whisper_init_from_file_with_params_no_state: loading model from 'C:\Users\93923\AppData\Local\pywhispercpp\pywhispercpp\models\ggml-large-v3.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
CUDA error: %s: found %d CUDA devices:

  current device: 0, in function ggml_cuda_init at E:\2025Project\pywhispercpp\whisper.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:156
  cuDeviceGet(&device, id)
E:\2025Project\pywhispercpp\whisper.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:70: CUDA error

**Comment by absadiki** [comment]
@zhanghongyong123456, please try to compile with the no-repair-wheel flag and give it another try:
```shell
NO_REPAIR=1 GGML_CUDA=1 pip install .
```

**Comment by zhanghongyong123456** [comment]
> [@zhanghongyong123456](https://github.com/zhanghongyong123456), please try to compile with the no-repair-wheel flag and give it another try:
> 
> NO_REPAIR=1 GGML_CUDA=1 pip install .

have same error
Python 3.10.16 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 16:19:12) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pywhispercpp.model import Model
>>> model = Model('large-v3', print_realtime=False, print_progress=False)

**Comment by absadiki** [comment]
Have you tried compiling whisper.cpp ? is it working ?

**Comment by pformoso-deus-ai** [comment]
I'm having the same issue running on Ubuntu 24.04 with Cuda 12.8 

Whisper.cpp runs and compiles perfectly for me. Below a complete dump from GDB

`whisper_init_from_file_with_params_no_state: loading model from '/home/pablo.formosoestrada/.local/share/pywhispercpp/models/ggml-large-v3.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    yes
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: yes
ggml_cuda_init: found 1 CUDA devices:
CUDA error: initialization error
  current device: 0, in function ggml_cuda_init at /tmp/pip-req-build-a5lnyal9/whisper.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:156
  cuDeviceGet(&device, id)
/tmp/pip-req-build-a5lnyal9/whisper.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:70: CUDA error
[New LWP 1889]
warning: File "/home/pablo.formosoestrada/.pyenv/versions/3.11.12/bin/python3.11-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /home/pablo.formosoestrada/.pyenv/versions/3.11.12/bin/python3.11-gdb.py
line to your configuration file "/home/pablo.formosoestrada/.config/gdb/gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/pablo.formosoestrada/.config/gdb/gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x0000757bc63107e3 in __GI___wait4 (pid=1901, stat_loc=0x7ffd1a04c014, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
warning: 30	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory
#0  0x0000757bc63107e3 in __GI___wait4 (pid=1901, stat_loc=0x7ffd1a04c014, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x0000757bb89525ba in ggml_abort () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libggml-base-2e1a6ed5.so
#2  0x0000757bb405ebe7 in ggml_cuda_error(char const*, char const*, char const*, int, char const*) () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libggml-cuda-3bb818f8.so
#3  0x0000757bb405f1fd in ggml_cuda_init() () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libggml-cuda-3bb818f8.so
#4  0x0000757bb4060392 in ggml_cuda_info() () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libggml-cuda-3bb818f8.so
#5  0x0000757bb406a28a in ggml_backend_cuda_reg () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libggml-cuda-3bb818f8.so
#6  0x0000757bc3a84e69 in get_reg() () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libggml-b98fd210.so
#7  0x0000757bc3a8521d in ggml_backend_dev_count () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libggml-b98fd210.so
#8  0x0000757bb8db96ad in whisper_init_with_params_no_state () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libwhisper-f19a4489.so.1.7.4
#9  0x0000757bb8db9b51 in whisper_init_from_file_with_params_no_state () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libwhisper-f19a4489.so.1.7.4
#10 0x0000757bb8db9d6e in whisper_init_from_file_with_params () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libwhisper-f19a4489.so.1.7.4
#11 0x0000757bb8db9e00 in whisper_init_from_file () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libwhisper-f19a4489.so.1.7.4
#12 0x0000757bb93c048d in ?? () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/_pywhispercpp.cpython-311-x86_64-linux-gnu.so
#13 0x0000757bb93d2716 in ?? () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/_pywhispercpp.cpython-311-x86_64-linux-gnu.so
#14 0x0000757bb93c56d5 in ?? () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/_pywhispercpp.cpython-311-x86_64-linux-gnu.so
#15 0x0000757bc67b5603 in cfunction_call (func=0x757bb8e35e90, args=<optimized out>, kwargs=<optimized out>) at Objects/methodobject.c:542
warning: 542	Objects/methodobject.c: No such file or directory
#16 0x0000757bc67606d1 in _PyObject_MakeTpCall (tstate=0x757bc6b916b8 <_PyRuntime+166328>, callable=callable@entry=0x757bb8e35e90, args=args@entry=0x757bc6c18188, nargs=1, keywords=keywords@entry=0x0) at Objects/call.c:214
warning: 214	Objects/call.c: No such file or directory
#17 0x0000757bc6760d4f in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x757bc6c18188, callable=0x757bb8e35e90, tstate=<optimized out>) at ./Include/internal/pycore_call.h:90
warning: 90	./Include/internal/pycore_call.h: No such file or directory
#18 0x0000757bc670347c in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:4769
warning: 4769	Python/ceval.c: No such file or directory
#19 0x0000757bc68619f8 in _PyEval_EvalFrame (throwflag=0, frame=0x757bc6c18088, tstate=0x757bc6b916b8 <_PyRuntime+166328>) at ./Include/internal/pycore_ceval.h:73
warning: 73	./Include/internal/pycore_ceval.h: No such file or directory
#20 _PyEval_Vector (tstate=0x757bc6b916b8 <_PyRuntime+166328>, func=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:6434
warning: 6434	Python/ceval.c: No such file or directory
#21 0x0000757bc67608c2 in _PyObject_FastCallDictTstate (tstate=tstate@entry=0x757bc6b916b8 <_PyRuntime+166328>, callable=callable@entry=0x757ba7ffa840, args=args@entry=0x7ffd1a04d520, nargsf=nargsf@entry=2, kwargs=kwargs@entry=0x757bc316fa80) at Objects/call.c:152
warning: 152	Objects/call.c: No such file or directory
#22 0x0000757bc6760ba0 in _PyObject_Call_Prepend (tstate=tstate@entry=0x757bc6b916b8 <_PyRuntime+166328>, callable=callable@entry=0x757ba7ffa840, obj=obj@entry=0x757bc5dd1610, args=args@entry=0x757bc5d23f10, kwargs=kwargs@entry=0x757bc316fa80) at Objects/call.c:482
482	in Objects/call.c
#23 0x0000757bc67db43a in slot_tp_init (self=0x757bc5dd1610, args=0x757bc5d23f10, kwds=0x757bc316fa80) at Objects/typeobject.c:7855
warning: 7855	Objects/typeobject.c: No such file or directory
#24 0x0000757bc67d1059 in type_call (type=<optimized out>, args=0x757bc5d23f10, kwds=0x757bc316fa80) at Objects/typeobject.c:1103
1103	in Objects/typeobject.c
#25 0x0000757bc67606d1 in _PyObject_MakeTpCall (tstate=0x757bc6b916b8 <_PyRuntime+166328>, callable=callable@entry=0x61eb283cf000, args=args@entry=0x757bc6c18078, nargs=1, keywords=keywords@entry=0x757bc610ab90) at Objects/call.c:214
warning: 214	Objects/call.c: No such file or directory
#26 0x0000757bc6760d4f in _PyObject_VectorcallTstate (kwnames=0x757bc610ab90, nargsf=<optimized out>, args=0x757bc6c18078, callable=0x61eb283cf000, tstate=<optimized out>) at ./Include/internal/pycore_call.h:90
warning: 90	./Include/internal/pycore_call.h: No such file or directory
#27 0x0000757bc670347c in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:4769
warning: 4769	Python/ceval.c: No such file or directory
#28 0x0000757bc6861884 in _PyEval_EvalFrame (throwflag=0, frame=0x757bc6c18020, tstate=0x757bc6b916b8 <_PyRuntime+166328>) at ./Include/internal/pycore_ceval.h:73
warning: 73	./Include/internal/pycore_ceval.h: No such file or directory
#29 _PyEval_Vector (args=0x0, argcount=0, kwnames=0x0, locals=0x757bc61f28c0, func=0x757bc61ce0c0, tstate=0x757bc6b916b8 <_PyRuntime+166328>) at Python/ceval.c:6434
warning: 6434	Python/ceval.c: No such file or directory
#30 PyEval_EvalCode (co=co@entry=0x61eb27672530, globals=globals@entry=0x757bc61f28c0, locals=locals@entry=0x757bc61f28c0) at Python/ceval.c:1148
1148	in Python/ceval.c
#31 0x0000757bc68ac2e9 in run_eval_code_obj (locals=0x757bc61f28c0, globals=0x757bc61f28c0, co=0x61eb27672530, tstate=0x757bc6b916b8 <_PyRuntime+166328>) at Python/pythonrun.c:1741
warning: 1741	Python/pythonrun.c: No such file or directory
#32 run_mod (mod=<optimized out>, filename=filename@entry=0x757bc6196630, globals=globals@entry=0x757bc61f28c0, locals=locals@entry=0x757bc61f28c0, flags=flags@entry=0x7ffd1a04d918, arena=arena@entry=0x757bc611b770) at Python/pythonrun.c:1762
1762	in Python/pythonrun.c
#33 0x0000757bc68adc7e in pyrun_file (flags=0x7ffd1a04d918, closeit=1, locals=0x757bc61f28c0, globals=0x757bc61f28c0, start=257, filename=0x757bc6196630, fp=<optimized out>) at Python/pythonrun.c:1657
1657	in Python/pythonrun.c
#34 _PyRun_SimpleFileObject (fp=fp@entry=0x61eb27607370, filename=filename@entry=0x757bc6196630, closeit=closeit@entry=1, flags=flags@entry=0x7ffd1a04d918) at Python/pythonrun.c:440
440	in Python/pythonrun.c
#35 0x0000757bc68ae300 in _PyRun_AnyFileObject (fp=0x61eb27607370, filename=filename@entry=0x757bc6196630, closeit=closeit@entry=1, flags=flags@entry=0x7ffd1a04d918) at Python/pythonrun.c:79
79	in Python/pythonrun.c
#36 0x0000757bc68cf350 in pymain_run_file_obj (skip_source_first_line=0, filename=0x757bc6196630, program_name=0x757bc612d1b0) at Modules/main.c:360
warning: 360	Modules/main.c: No such file or directory
#37 pymain_run_file (config=0x757bc6b77700 <_PyRuntime+59904>) at Modules/main.c:379
379	in Modules/main.c
#38 pymain_run_python (exitcode=0x7ffd1a04d910) at Modules/main.c:605
605	in Modules/main.c
#39 Py_RunMain () at Modules/main.c:684
684	in Modules/main.c
#40 0x0000757bc68cf8ee in pymain_main (args=0x7ffd1a04da30) at Modules/main.c:714
714	in Modules/main.c
#41 Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:738
738	in Modules/main.c
#42 0x0000757bc622a1ca in __libc_start_call_main (main=main@entry=0x61eaf8eb0060 <main>, argc=argc@entry=2, argv=argv@entry=0x7ffd1a04dbc8) at ../sysdeps/nptl/libc_start_call_main.h:58
warning: 58	../sysdeps/nptl/libc_start_call_main.h: No such file or directory
#43 0x0000757bc622a28b in __libc_start_main_impl (main=0x61eaf8eb0060 <main>, argc=2, argv=0x7ffd1a04dbc8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd1a04dbb8) at ../csu/libc-start.c:360
warning: 360	../csu/libc-start.c: No such file or directory
#44 0x000061eaf8eb0095 in _start ()
[Inferior 1 (process 1842) detached]
Aborted (core dumped)`

**Comment by absadiki** [comment]
@pformoso-deus-ai 
> https://github.com/absadiki/pywhispercpp/pull/3 0x0000757bb405f1fd in ggml_cuda_init() () from /home/pablo.formosoestrada/.pyenv/versions/3.11.12/lib/python3.11/site-packages/pywhispercpp.libs/libggml-cuda-3bb818f8.so

Seems you are compiling with the repair wheel enabled. 
please try to compile with the no-repair-wheel flag as I mentioned above.

**Comment by pformoso-deus-ai** [comment]
Thanks for the response @absadiki 

I was able to compile it with no issues once I updated the Whipser.cpp submodule. I'm not able to have a root cause, but I reasoned because I was able to compile and make whisper.cpp to work whithout the wrapper.

This other issues https://github.com/absadiki/pywhispercpp/issues/95 helped too.  

Can be close from my end.

**Comment by absadiki** [comment]
Thanks @pformoso-deus-ai  for the update! Glad to hear it's working now.
