### ISSUE TITLE
Problem with CUDA support

### ISSUE THREAD

**Issue by KianRK** [absadiki/pywhispercpp#95]
Hi, I am trying to run on Ubuntu 20.04 with CUDA support.

I created a minimal python script

`from pywhispercpp.model import Model

model = Model('small', models_dir = "models", language='de', translate=False, print_progress=False)

segments = model.transcribe('test_samples.wav', language='de')

transcribed_text = "".join(segment.text for segment in segments)
model.print_timings()

with open ("model_small_transcription.txt", "w") as file:
    file.write(transcribed_text)

`

which works fine with the normal installation.
But since I want GPU support I created a fresh venv and installed with GPU support. When I now run the script I get:

`python whisper_cpp_small.py 
whisper_init_from_file_with_params_no_state: loading model from '/home/user/whisper_benchmark/models/ggml-small.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 3 (small)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
CUDA error: initialization error
  current device: 0, in function ggml_cuda_init at /tmp/pip-req-build-wqj_dne6/whisper.cpp/ggml/src/ggml-cuda.cu:187
  cuDeviceGet(&device, id)
/tmp/pip-req-build-wqj_dne6/whisper.cpp/ggml/src/ggml-cuda.cu:101: CUDA error
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No stack.
The program is not being run.
Aborted (core dumped)`

And after temporarily setting ptrace to 0 and allowing every process to attach other processes with 
`echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
`

I get 
` python whisper_cpp_small.py 
whisper_init_from_file_with_params_no_state: loading model from '/home/user/whisper_benchmark/models/ggml-small.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 3 (small)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
CUDA error: initialization error
  current device: 0, in function ggml_cuda_init at /tmp/pip-req-build-wqj_dne6/whisper.cpp/ggml/src/ggml-cuda.cu:187
  cuDeviceGet(&device, id)
/tmp/pip-req-build-wqj_dne6/whisper.cpp/ggml/src/ggml-cuda.cu:101: CUDA error
[New LWP 49461]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f0b158eac7f in __GI___wait4 (pid=49462, stat_loc=0x7fffe7736e74, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
#0  0x00007f0b158eac7f in __GI___wait4 (pid=49462, stat_loc=0x7fffe7736e74, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x00007f0b026ed841 in ggml_abort () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/pywhispercpp.libs/libggml-8e1bb5e4.so
#2  0x00007f0b027c4906 in ggml_cuda_error(char const*, char const*, char const*, int, char const*) () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/pywhispercpp.libs/libggml-8e1bb5e4.so
#3  0x00007f0b027c5343 in ggml_cuda_init() () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/pywhispercpp.libs/libggml-8e1bb5e4.so
#4  0x00007f0b027c5e12 in ggml_cuda_info() () from /home/uservenvs/benchmark_whisper/lib/python3.11/site-packages/pywhispercpp.libs/libggml-8e1bb5e4.so
#5  0x00007f0b027c88bd in ggml_backend_cuda_get_device_count () from /home/user/venvs/benchmark_whisper/lib/python3.11/site-packages/pywhispercpp.libs/libggml-8e1bb5e4.so
#6  0x00007f0b027c891b in ggml_backend_cuda_buffer_type () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/pywhispercpp.libs/libggml-8e1bb5e4.so
#7  0x00007f0b14878f4b in whisper_model_load(whisper_model_loader*, whisper_context&) () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/pywhispercpp.libs/libwhisper-744a19a8.so.1.6.2
#8  0x00007f0b1487ae39 in whisper_init_with_params_no_state () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/pywhispercpp.libs/libwhisper-744a19a8.so.1.6.2
#9  0x00007f0b1487b1ba in whisper_init_from_file_with_params_no_state () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/pywhispercpp.libs/libwhisper-744a19a8.so.1.6.2
#10 0x00007f0b1487b3d3 in whisper_init_from_file_with_params () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/pywhispercpp.libs/libwhisper-744a19a8.so.1.6.2
#11 0x00007f0b1487b454 in whisper_init_from_file () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/pywhispercpp.libs/libwhisper-744a19a8.so.1.6.2
#12 0x00007f0b148e135d in ?? () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/_pywhispercpp.cpython-311-x86_64-linux-gnu.so
#13 0x00007f0b148eb74f in ?? () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/_pywhispercpp.cpython-311-x86_64-linux-gnu.so
#14 0x00007f0b148df263 in ?? () from /home/user/.venvs/benchmark_whisper/lib/python3.11/site-packages/_pywhispercpp.cpython-311-x86_64-linux-gnu.so
#15 0x00000000005edda9 in ?? ()
#16 0x00000000006390bd in _PyObject_MakeTpCall ()
#17 0x000000000058ec81 in _PyEval_EvalFrameDefault ()
#18 0x000000000063793e in _PyFunction_Vectorcall ()
#19 0x00000000005c76c1 in ?? ()
#20 0x00000000005d6834 in ?? ()
#21 0x0000000000639170 in _PyObject_MakeTpCall ()
#22 0x000000000058ec81 in _PyEval_EvalFrameDefault ()
#23 0x00000000006e142f in ?? ()
#24 0x00000000006e16b7 in PyEval_EvalCode ()
#25 0x00000000006bb667 in ?? ()
#26 0x00000000006bb6f0 in ?? ()
#27 0x00000000006bb90b in ?? ()
#28 0x00000000006bbed4 in _PyRun_SimpleFileObject ()
#29 0x00000000006bbf97 in _PyRun_AnyFileObject ()
#30 0x00000000006b3cfc in Py_RunMain ()
#31 0x00000000006b3ead in Py_BytesMain ()
#32 0x00007f0b1582c083 in __libc_start_main (main=0x52bf40, argc=2, argv=0x7fffe7738758, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffe7738748) at ../csu/libc-start.c:308
308	../csu/libc-start.c: No such file or directory.
#33 0x0000000000669c6e in _start ()
[Inferior 1 (process 49453) detached]
Aborted (core dumped)
`

I know this looks like a CUDA related Problem but in other applications CUDA runs just fine.

Output of nvcc --version:

`nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Oct_29_23:50:19_PDT_2024
Cuda compilation tools, release 12.6, V12.6.85
Build cuda_12.6.r12.6/compiler.35059454_0
`

nvidia-smi:

`nvidia-smi
Sun Jan 19 17:47:00 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.05              Driver Version: 560.35.05      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA T500                    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8             N/A / ERR!  |      13MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1421      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A      2429      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+
`

and also torch.cuda.is_available() returns true.

Any ideas what the problem might be?

**Comment by absadiki** [comment]
Seems like a cuda issue or `whisper.cpp` issue.
Have you tried compiling `whisper.cpp`  on its own ?  is it working ?

**Comment by KianRK** [comment]
After your reply I compiled whisper.cpp with gpu support and got an error that my cmake version was too low.
I then upgraded cmake and then successfully compiled whisper.cpp with gpu support and it runs on gpu as expected.

I then reinstalled pywhispercpp with `GGML_CUDA=1 pip install git+https://github.com/absadiki/pywhispercpp`, but still got the same errors with ptrace_scope 0 and 1.

**Comment by absadiki** [comment]
If you tested it and it runs successfully, I would suggest cloning the repository, creating a virtual environment for it, cd to the whisper.cpp submodule, pulling to the latest commit (or the same commit that works for you), then compiling and testing again.

If it works, please let me know so I can update the submodule here as well.

**Comment by KianRK** [comment]
When I compiled whisper.cpp by itself I used the master branch.

After your reply I cloned the pywhispercpp repo in my home dir and ran 
`
git submodule update --init
`

and then switched in the whisper.cpp submodule to the master branch.

Then I ran `GGML_CUDA=1 pip install pywhispercpp/`  from my home dir but it failed 

```
[91/96] Building CUDA object whisper.cpp/ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-vec-f32-instance-hs256-f16-f16.cu.o
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/krajabi/.venvs/pywhispercpp/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/krajabi/.venvs/pywhispercpp/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/krajabi/.venvs/pywhispercpp/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 232, in <module>
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 186, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 983, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "<string>", line 188, in run
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/command/bdist_wheel.py", line 379, in run
          self.run_command("build")
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 339, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 136, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 339, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 365, in run
          self.build_extensions()
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 481, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-rmwl59nn/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 507, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 157, in build_extension
        File "/usr/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pywhispercpp
Failed to build pywhispercpp
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pywhispercpp)
```

Also, even though it seems to be a problem with the custom CUDA kernels and I don't know if this is relevant:
 the build commands for CUDA support in the master branch of whisper.cpp differ from the commit you integrated as a submodule.
the master uses:

`cmake -B build -DGGML_CUDA=1
cmake --build build -j --config Release`

whereas commit [9e3c534]

`GGML_CUDA=1 make -j`

**Comment by absadiki** [comment]
Yeah, something is weird. In your first comment, I can see that it was successfully compiling, at least. 
I'll try to investigate this when I get some time.

**Comment by KianRK** [comment]
Ok, thanks for your support. Would be really nice if it worked. Next week I will also try from a different machine and will see if it somehow still is a device specific problem.

**Comment by absadiki** [comment]
I think there is something wrong with the repair wheel logic and the cuda shared libraries. 
I tried to make this optional. Probably give it a try and let me know how it goes.
Please cd to the repo folder, checkout to the [fix/repair-wheel](https://github.com/absadiki/pywhispercpp/tree/fix/repair-wheel) branch, pull the latest commit and try to compile again with:
`NO_REPAIR=1 GGML_CUDA=1 pip install .`

**Comment by KianRK** [comment]
I freshly cloned the repository and switched to the fix/repair-wheel branch. For compilation I had to run `git submodule update --init`, otherwise I got an error that a CMakeList,txt was missing in whisper.cpp/.

After that I  ran `NO_REPAIR=1 GGML_CUDA=1 pip install .` and it successfully compiled and installed.

When running the minimal script I posted, it ran the model on the GPU.

So now everything works as intended.

Thanks again for your support!

**Comment by absadiki** [comment]
You are welcome :) , I will merge it then into the main branch.

**Comment by lxe** [comment]
I'm still observing this. This is from a fresh install with cleaned uv cache:

```console
~/yapyap master !3 ?3                                                                                                                                                     ✘ IOT   yapyap
❯ GGML_CUDA=1 uv pip install git+https://github.com/absadiki/pywhispercpp    
Resolved 9 packages in 770ms
Audited 9 packages in 0.01ms

~/yapyap master !3 ?3                                                                                                                                                             yapyap
❯ python -c "from pywhispercpp.model import Model; Model('tiny')"
whisper_init_from_file_with_params_no_state: loading model from '/home/lxe/.local/share/pywhispercpp/models/ggml-tiny.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
CUDA error: initialization error
  current device: 0, in function ggml_cuda_init at /home/lxe/.cache/uv/git-v0/checkouts/7d2cb751e4e0ea8c/f6ae8b0/whisper.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:156
  cuDeviceGet(&device, id)
/home/lxe/.cache/uv/git-v0/checkouts/7d2cb751e4e0ea8c/f6ae8b0/whisper.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:70: CUDA error
[New LWP 50188]
warning: Loadable section ".dynstr" outside of ELF segments
  in /home/lxe/.local/share/uv/python/cpython-3.12.11-linux-x86_64-gnu/bin/python3.12

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007ff36ca9f042 in ?? () from /usr/lib/libc.so.6
#0  0x00007ff36ca9f042 in ?? () from /usr/lib/libc.so.6
#1  0x00007ff36ca931ac in ?? () from /usr/lib/libc.so.6
#2  0x00007ff36ca931f4 in ?? () from /usr/lib/libc.so.6
#3  0x00007ff36cb03dcf in wait4 () from /usr/lib/libc.so.6
#4  0x00007ff36bfc5111 in ggml_abort () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp.libs/libggml-base-2d941357.so
#5  0x00007ff36baa86a1 in ggml_cuda_error(char const*, char const*, char const*, int, char const*) () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp.libs/libggml-cuda-53cc4b8f.so
#6  0x00007ff36baa8cbb in ggml_cuda_init() () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp.libs/libggml-cuda-53cc4b8f.so
#7  0x00007ff36baa9d01 in ggml_cuda_info() () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp.libs/libggml-cuda-53cc4b8f.so
#8  0x00007ff36bab5465 in ggml_backend_cuda_reg () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp.libs/libggml-cuda-53cc4b8f.so
#9  0x00007ff36cc37d9e in get_reg() () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp.libs/libggml-0847e717.so
#10 0x00007ff36cc380b9 in ggml_backend_dev_count () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp.libs/libggml-0847e717.so
#11 0x00007ff36c15531a in whisper_init_with_params_no_state () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp.libs/libwhisper-38b51b4e.so.1.7.4
#12 0x00007ff36c1557c6 in whisper_init_from_file_with_params_no_state () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp.libs/libwhisper-38b51b4e.so.1.7.4
#13 0x00007ff36c15967a in whisper_init_from_file_with_params () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp.libs/libwhisper-38b51b4e.so.1.7.4
#14 0x00007ff36c1596fa in whisper_init_from_file () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp.libs/libwhisper-38b51b4e.so.1.7.4
#15 0x00007ff36c1c6459 in ?? () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/_pywhispercpp.cpython-312-x86_64-linux-gnu.so
#16 0x00007ff36c1db818 in ?? () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/_pywhispercpp.cpython-312-x86_64-linux-gnu.so
#17 0x00007ff36c1c37ad in ?? () from /home/lxe/yapyap/.venv/lib/python3.12/site-packages/_pywhispercpp.cpython-312-x86_64-linux-gnu.so
#18 0x0000000001a0647c in cfunction_call ()
#19 0x0000000001a16bce in _PyEval_EvalFrameDefault ()
#20 0x0000000001a61b22 in slot_tp_init ()
#21 0x0000000001a0282b in type_call ()
#22 0x0000000001a16b63 in _PyEval_EvalFrameDefault ()
#23 0x0000000001a935a2 in PyEval_EvalCode ()
#24 0x0000000001aaa982 in run_mod.llvm ()
#25 0x0000000001aaa800 in PyRun_StringFlags ()
#26 0x0000000001b4917d in PyRun_SimpleStringFlags ()
#27 0x0000000001b49111 in pymain_run_command ()
#28 0x0000000001b489e7 in Py_RunMain ()
#29 0x0000000001bd06fa in pymain_main.llvm ()
#30 0x0000000001bd04ed in main ()
[Inferior 1 (process 50164) detached]
zsh: IOT instruction (core dumped)  python -c "from pywhispercpp.model import Model; Model('tiny')"
```

I attempted a fix:

```
NO_REPAIR=1 GGML_CUDA=1 uv pip install git+https://github.com/absadiki/pywhispercpp --no-cache --reinstall 
```

But now I get:

```
❯ python -c "from pywhispercpp.model import Model; Model('tiny')"                                           
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lxe/yapyap/.venv/lib/python3.12/site-packages/pywhispercpp/model.py", line 15, in <module>
    import _pywhispercpp as pw
ImportError: libwhisper.so.1: cannot open shared object file: No such file or directory
```

Now I have to manually set LD_LIBRARY_PATH:

```
❯ LD_LIBRARY_PATH=$(python -c "import site; print(site.getsitepackages()[0])") python -c "from pywhispercpp.model import Model; Model('tiny')"  

whisper_init_from_file_with_params_no_state: loading model from '/home/lxe/.local/share/pywhispercpp/models/ggml-tiny.bin'
```

Something is definitely amiss

**Comment by absadiki** [comment]
@lxe, I think uv runs in a more isolated environment and doesn’t automatically inherit LD_LIBRARY_PATH. Use pip instead.

**Comment by lxe** [comment]
@absadiki I don't think that's quite the root cause. I think it's due to how recompilation and wheel repair is handled. I have a PR out that potentially addresses this.
